---
- name: Gather information from routers
  hosts: group_cisco_routers
  gather_facts: yes
  tasks:
    - name: Gather router facts
      cisco.ios.ios_facts:
      register: cisco_facts
    - name: Display router facts
      ansible.builtin.debug:
        var: cisco_facts
