---
- name: Zabbix Interface Down
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Handle Interface Down
      condition: event.payload.trigger_name is defined
      action:
        run_job_template:
          name: "TEM_CML_LAB1"
          organization: "Network_Team_CML"
